### ISSUE TITLE
在vite4.4.6版本  只在开发环境有效 打包预览无效 

### ISSUE THREAD

**Issue by yck-rgb** [pekonchan/rollup-plugin-i18n-auto#4]
在vite4.4.6版本  只在开发环境有效 打包预览无效 
只测试了这个版本  不知道是不是其他版本也是都无效

**Comment by pekonchan** [comment]
> 在vite4.4.6版本 只在开发环境有效 打包预览无效 只测试了这个版本 不知道是不是其他版本也是都无效

无效是指所有功能无效还是具体某个功能无效呢？

功能有：提取关键词、转换翻译、自动翻译

**Comment by pekonchan** [comment]
by the way， 这里有个demo地址 https://github.com/pekonchan/rollup-plugin-i18n-auto-demo

**Comment by pekonchan** [comment]
> 在vite4.4.6版本 只在开发环境有效 打包预览无效 只测试了这个版本 不知道是不是其他版本也是都无效

目前是否还有问题 @yck-rgb

**Comment by pekonchan** [comment]
因问题已许久未回复，先关闭此issue
