### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by yzfpf** [pekonchan/rollup-plugin-i18n-auto#6]
[plugin:i18n-auto] Unexpected token, expected "," (1:15) - make sure this is an expression.

![image](https://github.com/pekonchan/rollup-plugin-i18n-auto/assets/170693014/6e8b7724-0357-4a47-86c4-8b0332243a3c)

**Comment by pekonchan** [comment]
这个插件要用在vue插件后面。 vue插件会先对vue代码转成js，然后这个插件就会对js进行处理。

**Comment by pekonchan** [comment]
我这里有个使用demo  @yzfpf

**Comment by yzfpf** [comment]
@pekonchan 现在每次重新启动项目，中文都会被重新提取一次，其实有没有可能做增量编译的，比如第一次编译过了有结果，第二次编译的话，只变更有变化的数据并插入到末尾

**Comment by pekonchan** [comment]
@yzfpf 想了解下什么表现会让你觉得被重新提取，我处理的时候其实是增量的

**Comment by yzfpf** [comment]
@pekonchan 可能是格式化的问题，每次重新生成都变成一行的话，我有点看不出差别，看起来就像是被全量重新处理了，如果可以按行缩进格式化一下的话，看起来会直观点。

**Comment by pekonchan** [comment]
@yzfpf 嗯嗯，是格式化的问题。实际上处理是增量的，不然每次key值都是变化的。 只是每次回写到json文件时我都是格式化压缩了。 

一般最终使用上还是压缩形态，节省体积。所以默认都是压缩成一行这样。 后续可以考虑加个配置是否压缩😁

**Comment by pekonchan** [comment]
第一个问题是否已经解决？ 即改成放在vue插件后再使用本插件。 如已解决我关闭此issue。 后续有其他问题和建议欢迎再提issue

**Comment by yzfpf** [comment]
@pekonchan 已解决，感谢
