### ISSUE TITLE
模板字符串识别可能有些问题

### ISSUE THREAD

**Issue by Banana-energy** [pekonchan/rollup-plugin-i18n-auto#9]
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto/assets/49467518/257372c8-6fcd-463d-827e-6eb5f210d201)
对应这种字符串会报错
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto/assets/49467518/37ca8eaf-8068-416e-940e-b23d3401bc3c)

**Comment by Banana-energy** [comment]
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto/assets/49467518/a4cd256a-e5e0-4f6a-ba7e-faad5e5d0aac)
版本0.1.3

**Comment by pekonchan** [comment]
demo 工程更新了例子，也是按照你这种写法，没能复现问题哦 https://github.com/pekonchan/rollup-plugin-i18n-auto-demo/commit/bfb34b1d2354de0ac9f91fcd2a3ec2ca7eb7cf10 

你可以拉这个demo工程本地跑一下试下看是否可以。

若demo工程可以，你的项目工程不行的话，确认下node_modules里安装的是最新的npm包。 0.1.4 或 0.1.3 ， 也有可能是项目工程哪些配置影响了。

若实在无法查明原因，还有一个解决办法，就是使用该插件，放在babel插件后面，这样babel会将模板字符串写法转成普通字符串拼接，再用该插件就没问题了

@Banana-energy

**Comment by Banana-energy** [comment]
测试使用ts可以复现
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto/assets/49467518/395e39f4-77ab-4c50-b27b-681d073cb598)
![image](https://github.com/pekonchan/rollup-plugin-i18n-auto/assets/49467518/0661b7f5-27dd-45d1-b0ae-4b114b2a6c11)

**Comment by pekonchan** [comment]
你这个截图是用demo工程些的ts对吧。 你新建个分支push上来，我拉你的分支看看  @Banana-energy

**Comment by Banana-energy** [comment]
直接在script上加lang="ts"就可以复现，我是用gitpod测试了一下，没有拉代码

**Comment by pekonchan** [comment]
我在demo工程上加了ts，仍然未能复现问题。可以提供一下nodejs的版本

**Comment by Banana-energy** [comment]
已提交demo，node版本18.18.0

**Comment by pekonchan** [comment]
我知道为啥了。之前代码里改过了。但是忘记打包发布。 只发布了源码。。。 

现在好了，请更新到0.1.5最新版
